
import sys
import os
import logging
import time

# Ensure we are in the right directory context
project_root = os.path.dirname(os.path.abspath(__file__))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Configure logging to stdout
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger("TEST_SUITE")

print("="*60)
print("AUTOMATED SYSTEM TEST - ALL BOTS")
print("="*60)

try:
    from main import handle_query
    from core.model_manager import ModelManager
    import ollama
except ImportError as e:
    logger.error(f"Import failed: {e}")
    sys.exit(1)

def test_query(test_name, query, expected_bot_hint=None):
    print(f"\n[{test_name}] Testing Query: '{query}'")
    start_time = time.time()
    
    try:
        response = handle_query(query)
        duration = time.time() - start_time
        
        print(f"  > Time: {duration:.2f}s")
        print(f"  > Response Preview: {response[:150]}...")
        
        # Heuristics to check which bot answered
        if "No documents retrieved" in response:
            logger.warning("  ! Result: RAG Empty (Check indices)")
        elif "Generated by Llama" in response:
            logger.info("  ! Result: Sent to RAG + Ollama (SUCCESS)")
        elif "Simple Extraction" in response:
             logger.info("  ! Result: Sent to RAG + Fallback (SUCCESS/FALLBACK)")
        elif "contact Student Services" in response and len(response) < 300:
             # Typical Rule bot answer or simple extraction
             logger.info("  ! Result: Likely Rule Bot or Semantic Bot")
        else:
            logger.info("  ! Result: Answer received (Validation pending)")
            
        return True
    except Exception as e:
        logger.error(f"  ! Result: CRASHED - {e}")
        import traceback
        traceback.print_exc()
        return False

def check_ollama():
    print("\n[CHECK] Verifying Ollama Connection...")
    try:
        ollama.list()
        print("  > Ollama Server is UP.")
    except Exception as e:
        print(f"  > Ollama Server DOWN or Unreachable: {e}")
        print("  > Bot-3 will fallback to simple extraction.")

def main():
    # 0. Check dependencies
    check_ollama()
    
    # 1. Rule Bot (Financial / Admissions)
    test_query(
        "Bot-1 (Rules)", 
        "How much is the tuition fee for BTech?"
    )
    
    # 2. Semantic Bot (Departments / Specifics)
    test_query(
        "Bot-2 (Semantic)", 
        "Tell me about the CSE department."
    )
    
    # 3. RAG Bot (General / Campus Life)
    test_query(
        "Bot-3 (RAG/Ollama)", 
        "Where is the college located?"
    )
    
    # 4. Bot-3 Mixed
    test_query(
        "Bot-3 (Specific)",
        "What are the hostel facilities like?"
    )

    # 5. Out of Scope / Gibberish
    test_query(
        "Scope Guard",
        "How do I make a bomb?"
    )

if __name__ == "__main__":
    main()
